### ISSUE TITLE
Completion list in the wrong order with lsp-mode

### ISSUE THREAD

**Issue by tpadioleau** [latex-lsp/texlab#227]
Hi,

I am having the same issue as #191 with `lsp-mode` on emacs. It seems to be related to a missing property `sortText` in the request. It could be fine even with the same `sortText` for every candidate.

Thanks,
Thomas

**Comment by kiennq** [comment]
I would be `sortText` instead of `insertText`.
> 	sortText?: string;
	/**
	 * A string that should be used when filtering a set of
	 * completion items. When `falsy` the label is used.
	 */

From the document of LSP, if the `sortText` is missing, then `label` is used for sorting the completion candidates.
So even with `isIncomplete` set to `true`, the order of completion item is still being changed.

**Comment by kiennq** [comment]
As @tpadioleau suggest, we should return increasing `sortText` instead, something like `0000`, `0001` ..., will guarantee the completion items order

**Comment by pfoerster** [comment]
Can you try running `texlab` with the `-vvvv` flag and post the log including an example document, here? Maybe, `texlab` returns the wrong list of items. Setting the `sortText` should not be necessary since according to the LSP spec, the label should be used if `sortText` is not set.

**Comment by tpadioleau** [comment]
Things recently changed in `lsp-mode` with this merge request https://github.com/emacs-lsp/lsp-mode/pull/1663, client-side sorting is now disabled when `sortText` is (globally) not set and when `isIncomplete` is `true`.
However I upload this log about the completion of `\begin` which shows many symbols that are not shown in VS. Do you know why ? [texlab.log](https://github.com/latex-lsp/texlab/files/4606502/texlab.log)

**Comment by efoerster** [comment]
Is this log from `lsp-mode` or `vscode`? However, I compared it to the log from `vscode` and they are essentially the same (only the `kind` field differs). Therefore, I think that there is something wrong with the fuzzy matching implementation of `lsp-mode`.

**Comment by kiennq** [comment]
> Is this log from `lsp-mode` or `vscode`? However, I compared it to the log from `vscode` and they are essentially the same (only the `kind` field differs). Therefore, I think that there is something wrong with the fuzzy matching implementation of `lsp-mode`

The different is that `vscode` still doing client filtering when `isIncomplete` is `true`. However, according to [this comment](https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-593330300) (from LSP specs owner), when `isIncomplete` is `true` (he is saying `isComplete` is `false`, same meaning though), client should stop filtering (i.e: fuzzy matching).

So `texlab` should either don't send those unrelated items, or stop setting `isIncomplete` and set proper `sortText`.

**Comment by tpadioleau** [comment]
> So `texlab` should either don't send those unrelated items, or stop setting `isIncomplete` and set proper `sortText`.

@efoerster Is there a reason these items appear ? They don't seem relevant in the first place ?

**Comment by pfoerster** [comment]
Can you give 38fabd6914ff297c94cf0b8c7951842beda5840d a shot, please? `texlab` now sets the `sortText` and irrelevant items are stripped from the completion list.
Note that, we cannot set `isIncomplete` to `false` as this would involve heavy performance penalties mainly on the client side. For example, VSCode does not appear to virtualize the list of completion items and crashes when we send too many items.

**Comment by kiennq** [comment]
> Note that, we cannot set `isIncomplete` to `false` as this would involve heavy performance penalties mainly on the client side.

Thanks for the insight. Out of curious, do you set `isIncomplete` to `false` when there's small number of items (< 100), and that's all possible completions?
I believe client side has cache mechanism that will not asking server for more items when `isInComplete` is `false`. So when the number of completions are small, setting that can greatly improve the performance, since no RPC needed anymore.

**Comment by pfoerster** [comment]
> Out of curious, do you set isIncomplete to false when there's small number of items (< 100), and that's all possible completions?

At the moment, we do not because but we have plans to do so. There are still a lot of performance optimizations left. We plan to greatly improve the completion performance with `3.0.0`

**Comment by tpadioleau** [comment]
> Can you give [38fabd6](https://github.com/latex-lsp/texlab/commit/38fabd6914ff297c94cf0b8c7951842beda5840d) a shot, please? `texlab` now sets the `sortText` and irrelevant items are stripped from the completion list.

I tried, I can see new `sortText` item but I still have a long list of candidates when typing `\beg` for example. What do you mean by irrelevant ?

Thanks

**Comment by pfoerster** [comment]
There was a bug that prevented the filtering from happening. Now, with bdc06110b49335369b39c7ea2ef730c584bda5aa, it should be fixed.

> What do you mean by irrelevant ?

Items, for which the text being completed is not included in the label in some form, are omitted from the completion list.

**Comment by tpadioleau** [comment]
With bdc06110b49335369b39c7ea2ef730c584bda5aa it seems to work well. We may close this issue if it is okay for everyone.

Thanks a lot

**Comment by clason** [comment]
I'm sorry to say that this change disabled fuzzy matching with https://github.com/haorenW1025/completion-nvim. (Just FYI, I realize that there's probably no strategy that will get optimal behavior with _all_ clients.)

**Comment by pfoerster** [comment]
> I'm sorry to say that this change disabled fuzzy matching with https://github.com/haorenW1025/completion-nvim.

That's definitely a problem. We should probably implement the fuzzy matching on the server-side.
I think I found a neat library that implements a fuzzy matching algorithm: https://docs.rs/crate/fuzzy-matcher/0.3.4

> I realize that there's probably no strategy that will get optimal behavior with all clients.

I think that is still possible. In the worst case, we can use the client identification LSP support to accomodate specific clients. Nevertheless, this should be fixable without hard-coding clients. While I am at it, I can make the completion a bit faster, too. There are still some optimizations left.

**Comment by clason** [comment]
I have to admit that this is a part of the LSP ecosystem I still don't quite understand: is filtering and sorting supposed to be server- or client-side? It seems that currently there's a wide mix of one or the other or both (or neither) around... It's particularly unclear for autocompletion (where completion is triggered by a trigger character and then refined as you type, and where performance is much more critical).

The library looks good, though! (Also, substring and case-insensitive matching would be useful, too.)

**Comment by kiennq** [comment]
> I have to admit that this is a part of the LSP ecosystem I still don't quite understand: is filtering and sorting supposed to be server- or client-side? It seems that currently there's a wide mix of one or the other or both (or neither) around... It's particularly unclear for autocompletion (where completion is triggered by a trigger character and then refined as you type, and where performance is much more critical).

I think you can follow the conversion in [this thread](https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-588172764).
According to the comment 
> If `CompletionList.isComplete` is set to false the client needs to trigger a new completion list request if the user types a character (client is not allowed to cache the result) allowing the server to return:
> 
> * a different set of completion items
> * with different sort and filter properties
> 
> Can you provide me with use cases where this still results in missing expressiveness (minus the fact that we need to set the `sortText` property)

So the filtering can be done (and should be supported) by both client and server. The condition for using the filtering can be different though.
For example, when `isComplete` is set to `false`, each new characters will trigger different set of completion items with different sort and filtering property. Thus, client side should probably not touch the returned list and display it as it, after sorting according to `sortText`.
However, once `isComplete` is `true`, client side can cache the list and do additional filtering to make sure the candidates are matched with what user typed.

**Comment by clason** [comment]
So the take-away message here is 

1. It's all-or-nothing: once the server starts messing with the list of candidates, _all_ filtering has to be done on their side.
2. There's no (documented, unambiguous) way to negotiate between client and server who is supposed to be responsible for filtering, so the user needs to be informed (read: inform themselves) and either enable/disable matching either in the client or the server (assuming that's supported at all).

I assume performance-wise, it's always preferable to have the server do the filtering? In this case, would it be possible to make the filtering configurable? (I assume that whether matches are fuzzy or case insensitive is very much a matter of taste...)

**Comment by kiennq** [comment]
> 1. It's all-or-nothing: once the server starts messing with the list of candidates, _all_ filtering has to be done on their side.

It's depend on how server want to mess with the list of candidates. If it returns a incomplete list of candidates, client *could* respect that and display the list as it. Else, client filtering logic can kick in and showing the candidate that most appropriated to what user typed.

 

> 2\. There's no (documented, unambiguous) way to negotiate between client and server who is supposed to be responsible for filtering, so the user needs to be informed (read: inform themselves) and  enable/disable matching either in the client or the server (assuming that's supported at all).

Yes, although I think that which side is doing filtering can be decided by `isIncomplete` property as I said before. AFAIK, vscode is doing filtering no matter what server returned, that make the `clangd` guys are very angry. From the comment that I quoted before, not filtering is more logical in that case though.

> assume performance-wise, it's always preferable to have the server do the filtering?

Not necessary, client side filtering can be done quite fast, although it's lacking information about the language that only server know. Always rely on server doing filtering can lead to serious perf degrade, since each key stroke require a RPC request.

**Comment by clason** [comment]
> Yes, although I think that which side is doing filtering can be decided by isIncomplete property as I said before. AFAIK, vscode is doing filtering no matter what server returned, that make the clangd guys are very angry. From the comment that I quoted before, not filtering is more logical in that case though.

Yes, but that didn't seem to be fully the consensus, and relying on such interpretations seems dangerous to me. (One thing I always liked about texlab -- beyond its massive usefulness for my actual job, naturally -- is that it's a "strictly by the books" server. That makes it very easy to implement and validate clients for.) So I'd still recommend being explicit about this (as well as handling `isIncomplete` correctly, of course).

**Comment by pfoerster** [comment]
Can you try the latest commit on the master branch, please? Irrelevant items should still be filtered out (and `isIncomplete` is set to `false`, if the completion list is small) and fuzzy matching should work again. In addition to that, the completion should be faster and fuzzy matching now works with VSCode, too.

**Comment by clason** [comment]
Works nicely for me (neovim builtin lsp + completion-nvim)! Thank you!
