### ISSUE TITLE
[Feature Suggestion] Provide (filtered) DocumentSymbols

### ISSUE THREAD

**Issue by clason** [latex-lsp/texlab#31]
(Another suggestion cribbed from vimtex, which provides this as part of a general "table of contents" functionality)

I notice that texlab currently doesn't seem to provide the Workspace/DocumentSymbol functionality (it's listed on the website, but I don't see how to access this from VS Code, and vim-lsp gives "Retrieving symbols not supported for tex"). It would be useful to return a list of all labels, which the client can present as a way to navigate the project -- especially if this list could be filtered to only show equations (and other math-mode environments), or sections (and other sectioning commands), or theorems (and other such environments). *EDIT:* For BibTeX files, the function could return a list of all bibkeys.

**Comment by clason** [comment]
Out of curiosity: What's the status of that? I believe this is now fully implemented, right? Or do you have further plans?

**Comment by clason** [comment]
@efoerster I think I understand now the issue with the `DocumentSymbol` vs `SymbolInformation`. In particular, it looks not as trivial as I thought to make the current DocumentSymbol consumer support the nested `DocumentSymbol`s. (These are used by VS Code to show the breadcrumbs, right?)

If it's not too much work, would it be possible to also implement the `WorkspaceSymbol` functionality to just return the flat list of `SymbolInformation`s? Then we can have full hierarchical information for clients that can deal with them (like VS Code) and a simpler list for clients that can't (like vim-lsp, for now)?

**Comment by pfoerster** [comment]
> If it's not too much work, would it be possible to also implement the WorkspaceSymbol functionality to just return the flat list of SymbolInformations? Then we can have full hierarchical information for clients that can deal with them (like VS Code) and a simpler list for clients that can't (like vim-lsp, for now)?

The `ClientCapabilities` include a flag that specifies whether the client supports hierarchical symbols so TexLab has to provide a flat list in case the client does not support this.

>  (These are used by VS Code to show the breadcrumbs, right?)

Yes, in addition to that, VSCode uses the symbols to show the outline of the document.

> Out of curiosity: What's the status of that? I believe this is now fully implemented, right? Or do you have further plans?

We have implemented an initial version that returns all (nested) sections and labels. We have plans to improve this further by providing the formatted references (for example the caption when referencing figures).

**Comment by clason** [comment]
> The ClientCapabilities include a flag that specifies whether the client supports hierarchical symbols so TexLab has to provide a flat list in case the client does not support this.

Every time I _think_ I understand how this works... ;)

Then something else must be blocking vim-lsp supporting `DocumentSymbol`s. I admit I was secretly hoping to sidestep that via `WorkspaceSymbol` (which is supposed to use `SymbolInformation` and actually seems closer in spirit to what vim-lsp does with it).

> We have implemented an initial version that returns all (nested) sections and labels. We have plans to improve this further by providing the formatted references (for example the caption when referencing figures).

Nice! I'm looking forward to it! (I'm really impressed in how fast texlab develops -- it quickly moved from something I was interested in checking out to a part of my workflow that I'd be sorry to miss. Thank you for that!)

**Comment by clason** [comment]
Commit https://github.com/latex-lsp/texlab/commit/cba5e283871c646830e3ddccb8be3c320eaccf17 made `DocumentSymbol` work with vim-lsp -- thank you!

Random observations:
1. On a multi-file document, it only shows symbols from the current file (which seems correct according to the specification, but a list of all symbols from all files could be useful as well -- maybe as `WorkSpaceSymbol`?).
2. Weirdly, I get the chapter label for the current file twice: once as a `module` first in the list, and once as a `field` _last_ in the list. But I assume that this an issue with vim-lsp, not texlab.
3. For bibtex files, the list would actually be more useful (to me, don't want to throw shade on other people's workflow) if it _didn't_ include each field (`title` etc.) -- these are usually single lines, so are more quickly navigated to via cursor movement from the bibkey than straight from the list.

(Feel free to ignore those.)

**Comment by clason** [comment]
Regarding 2, I just noticed that sections are also listed without labels, so I assume that the first `module` entry is from the `\chapter`, while the second `field` is from the label. Looking at the log, it looks like that label is indeed last in the server response, so maybe there _is_ some issue with the flattening by texlab? (Not that it's a major issue.)

**Comment by pfoerster** [comment]
> On a multi-file document, it only shows symbols from the current file (which seems correct according to the specification, but a list of all symbols from all files could be useful as well -- maybe as WorkSpaceSymbol?).

This does not seem to be possible with the current LSP spec. A `DocumentSymbol` does not have an `uri` field. `workspace/symbol` does not help either in this regard because you have to specify a non-empty query string.

> Regarding 2, I just noticed that sections are also listed without labels, so I assume that the first module entry is from the \chapter, while the second field is from the label. Looking at the log, it looks like that label is indeed last in the server response, so maybe there is some issue with the flattening by texlab? (Not that it's a major issue.)

This should now be fixed. Before the latest changes, TexLab did indeed include all labels (including section labels).

> For bibtex files, the list would actually be more useful (to me, don't want to throw shade on other people's workflow) if it didn't include each field (title etc.) -- these are usually single lines, so are more quickly navigated to via cursor movement from the bibkey than straight from the list.

With the latest changes, TexLab strips the BibTeX fields from the flat symbol list but not when using `DocumentSymbol`s.

> Nice! I'm looking forward to it! (I'm really impressed in how fast texlab develops -- it quickly moved from something I was interested in checking out to a part of my workflow that I'd be sorry to miss. Thank you for that!)

That is really nice to hear. Thank you for contributing so much!

**Comment by clason** [comment]
> This does not seem to be possible with the current LSP spec. A DocumentSymbol does not have an uri field. workspace/symbol does not help either in this regard because you have to specify a non-empty query string.

Clearly, I need to work on my reading skills... Would it be possible to query on `kind` (as in: list all equations/lemmas/sections)?

> This should now be fixed. Before the latest changes, TexLab did indeed include all labels (including section labels).

Can confirm! I do see something like
```
test.tex|23 col 1| unknown symbol 22 : Lemma
```
but that's probably something that needs to be fixed at the client level. For equations, I still see the label -- and I'm unsure myself if I don't prefer the labels to (only) the environment names. Can they be combined? What would be most useful here?

> With the latest changes, TexLab strips the BibTeX fields from the flat symbol list but not when using DocumentSymbols.

Great, much more useful (for me), thanks! (I noticed that strings (e.g., shorthands for journal names) also show up at the bottom -- which is fine -- but this led me to notice that the bibtex parser for hover does not resolve these strings: if you have something like 
```tex
@string{siamjopt = {SIAM Journal on Optimization}}
@article{author,
      author = {An Author},
      journal = siamjopt,
      pages = {1--14},
      title = {A paper},
      year = {2019},
  }
```
you get
```
Author, A. (2019). A paper. *Siamjopt*, 1–14.
```
instead of `*SIAM Journal on Optimization*`. No big deal considering the added complexity, probably.)

> That is really nice to hear. Thank you for contributing so much!

Hard to keep up with you :)

**Comment by pfoerster** [comment]
> but this led me to notice that the bibtex parser for hover does not resolve these strings

This part is done by an external library which does not support BibTeX strings and string concatenation unfortunately. However, it should be relatively easy to inline all strings before calling the library. We will work on that.

> but that's probably something that needs to be fixed at the client level. 

vim-lsp does not support the latest members of the SymbolKind enum. Nevertheless, I replaced all usages of EnumMember with Class so this should be fixed for now.

> Clearly, I need to work on my reading skills... Would it be possible to query on kind (as in: list all equations/lemmas/sections)?

This should be relatively easy to implement. I (or @efoerster) will work on this soon.

In addition to that, I updated the document symbols. The `detail` field now includes the label name.
Additionally, TexLab parses the AUX file if it is available and uses it to show the numbers of labels.
This can be used in combination with the `filterText`.

**Comment by clason** [comment]
> This part is done by an external library which does not support BibTeX strings and string concatenation unfortunately. However, it should be relatively easy to inline all strings before calling the library. We will work on that.

As I wrote, it's no big deal, but of course would look nicer :)

> vim-lsp does not support the latest members of the SymbolKind enum. Nevertheless, I replaced all usages of EnumMember with Class so this should be fixed for now.

Thank you! Do you have a link to the latest members? Then I'll open an issue for vim-lsp.

> In addition to that, I updated the document symbols. The detail field now includes the label name.
Additionally, TexLab parses the AUX file if it is available and uses it to show the numbers of labels.
This can be used in combination with the filterText.

💯 Awesome! Vim-lsp doesn't show the `detail`s on completion, but that's their problem. (There's an open PR, I'll see how it looks with that.) It does work fine (and looks neat) with `DocumentSymbols` and `Hover`.

One minor nitpick: for equations, it would look nicer (to me) to have `Equation (x.y)` (with parentheses), but I'm not sure if everyone would agree...

**Comment by pfoerster** [comment]
> One minor nitpick: for equations, it would look nicer (to me) to have Equation (x.y) (with parentheses), but I'm not sure if everyone would agree...

Equation references now include parentheses.

> Thank you! Do you have a link to the latest members? Then I'll open an issue for vim-lsp

The `SymbolKind` enumeration can be found here: https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol

**Comment by clason** [comment]
👍 (Issue opened, should be easy to fix. Feel free to go back to the SymbolKind you think fits best -- although `number` isn't bad!)

One more nitpick: Figures currently show as `x.y <caption>`; nicer would be `Figure x.y <caption>`. (And probably similarly for tables, I haven't checked those.)

**Comment by pfoerster** [comment]
> One more nitpick: Figures currently show as x.y <caption>; nicer would be Figure x.y <caption>. (And probably similarly for tables, I haven't checked those.)

Thanks! Figures, tables and listings are now supported.

> This part is done by an external library which does not support BibTeX strings and string concatenation unfortunately. However, it should be relatively easy to inline all strings before calling the library. We will work on that.

Now, BibTeX strings are inlined before calling the library so the example you provided should now work as intended. However, string concatenation is not supported yet.

**Comment by clason** [comment]
Great, thank you very much!

> Now, BibTeX strings are inlined before calling the library so the example you provided should now work as intended. However, string concatenation is not supported yet.

I didn't know that was even supported by BibTex... If I ever come across a use case, I (or somebody else that needs it) can open an issue about it.

> TexLab now provides a basic implementation of the workspace/symbol request.

💯 I tried it out, and it works nicely. Three questions:

1. It seems that chapters, sections etc. only get a number if they have a label next to it. Is this easy to include, or a more fundamental issue with how `workspace/symbol` works?
2. Similarly, environments only show up at all if they are labelled.
3. Is there a way to query on `kind`? They show up in the list, but I can't seem to use them for the query.

On a related note (sorry to keep piling these up on you), the completion items are (for me) always labeled `text` -- would it make sense and be possible to also use more `kind`s here as well (e.g., list chapter labels as `Class`, equation labels as `number` etc.? (Vim-lsp now includes the full list from the latest specification, so no need to restrict yourself on my account.)

Are the correspondences between LaTeX/BibTeX constructs and symbol/completion `kinds` documented somewhere? (Might be a good idea if full use is made of them.)

**Comment by pfoerster** [comment]
> It seems that chapters, sections etc. only get a number if they have a label next to it. Is this easy to include, or a more fundamental issue with how workspace/symbol works?

This should be relatively easy to implement, because the AUX file contains enough information to get the number of a figure/section/table/listing without a label.
The initial version of the request is looking at all labels currently in order to reuse code.

> Similarly, environments only show up at all if they are labelled.

Do you want to include all environments like (document, enumerate, ...) or only special environments like figures, tables, listings and equations?

> Is there a way to query on kind? They show up in the list, but I can't seem to use them for the query.

This is not possible at the moment, but I am working on it.

> On a related note (sorry to keep piling these up on you), the completion items are (for me) always labeled text -- would it make sense and be possible to also use more kinds here as well (e.g., list chapter labels as Class, equation labels as number etc.? (Vim-lsp now includes the full list from the latest specification, so no need to restrict yourself on my account.)

This looks like an issue of `vim-lsp` to me. TexLab only uses `text` if the client does not support the other kinds. Can you post the log of the `initialize` request please? It seems like `ClientCapabilities.textDocument.completion.completionItemKind.valueSet` is missing.

> Are the correspondences between LaTeX/BibTeX constructs and symbol/completion kinds documented somewhere? (Might be a good idea if full -- and consistent -- use is made of them.)

The kinds of `CompletionItem`s can be found here: https://github.com/latex-lsp/texlab/blob/master/src/completion/factory.rs

**Comment by clason** [comment]
> This should be relatively easy to implement, because the AUX file contains enough information to get the number of a figure/section/table/listing without a label.
The initial version of the request is looking at all labels currently in order to reuse code.

Makes sense. The numbers are not so critical, but if _all_ chapters/sections/etc. could be shown even without aux files (in this case without numbers), that would make this feature significantly more useful.

> Do you want to include all environments like (document, enumerate, ...) or only special environments like figures, tables, listings and equations?

That is a very good question. I'd say in order of usefulness, I'd like to see
1. Figures, Tables, Listings, Algorithms, etc. (i.e., float environments)
2. Theorems, Lemmas, Definitions etc. (i.e., amsthm environments)
3. Equations etc. 
4. Enumerate etc. (all others)
5. Document

I'd draw the line between "really useful" and "for the sake of completeness" somewhere around 3. (If these five get different `kind`s that can be used for filtering, it might be easier to just include all environments, though.)

> This is not possible at the moment, but I am working on it.

Good to know; I was wondering whether I was doing something wrong. Thanks!

> This looks like an issue of vim-lsp to me. TexLab only uses text if the client does not support the other kinds. Can you post the log of the initialize request please? It seems like ClientCapabilities.textDocument.completion.completionItemKind.valueSet is missing.

> This looks like an issue of vim-lsp to me. TexLab only uses text if the client does not support the other kinds. Can you post the log of the initialize request please? It seems like ClientCapabilities.textDocument.completion.completionItemKind.valueSet is missing.

Good call, that would explain it! The full response is here:

```
Wed Sep  4 11:52:57 2019:["--->", 5, "texlab", {"method": "initialize",         "params": {"rootUri": "XXX",         "capabilities": {"workspace": {"configuration": true, "applyEdit": true}},      "rootPath": "XXX", "processId": 45734,      "trace": "off"}}]
Wed Sep  4 11:52:57 2019:["<---", 5, "texlab", {"response": {"id": 1,           "jsonrpc": "2.0", "result": {"capabilities": {"documentHighlightProvider":      true, "hoverProvider": true, "documentLinkProvider": {"resolveProvider":        false}, "documentFormattingProvider": true, "textDocumentSync": {"save":        {"includeText": false}, "change": 1, "openClose": true},                        "foldingRangeProvider": true, "documentSymbolProvider": true,                   "workspaceSymbolProvider": true, "renameProvider": {"prepareProvider": true},   "definitionProvider": true, "completionProvider": {"resolveProvider": true,     "triggerCharacters": ["\\", "{", "}", "@", "/", " "]}, "referencesProvider":    true}}}, "request": {"id": 1, "jsonrpc": "2.0", "method": "initialize",         "params": {"rootUri": "XXX",         "capabilities": {"workspace": {"configuration": true, "applyEdit": true}},      "rootPath": "XXX", "processId": 45734,      "trace": "off"}}}]
Wed Sep  4 11:52:57 2019:["--->", 5, "texlab", {"method": "initialized",        "params": {}}]
```
Looks indeed like no `completionItemKind` -- I'll open an issue!

> The kinds of CompletionItems can be found here: https://github.com/latex-lsp/texlab/blob/master/src/completion/factory.rs

I was thinking of the mapping of LaTeX kinds to LSP generic `CompletionItemKind`s -- maybe list them in the documentation or the texlab github wiki; my plan is to request vim-lsp to allow specifying custom kinds to override the generic ones.

**Comment by clason** [comment]
> Looks indeed like no completionItemKind -- I'll open an issue!

Just to be on the safe side, what would the correct response look like?

**Comment by pfoerster** [comment]
> Just to be on the safe side, what would the correct response look like?

This is the message that VSCode sends when initializing the server.
Note that, there is a `valueSet` which contains all available `CompletionItemKind`s.
If this property is missing, then the server has to assume that only `text` and `reference` are supported.

```json
{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":10972,"rootPath":"d:\\latex-lsp\\texlab-dev","rootUri":"file:///d:/latex-lsp/texlab-dev","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"tagSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true},"callHierarchy":{"dynamicRegistration":true}},"window":{"workDoneProgress":true}},"trace":"off","workspaceFolders":[{"uri":"file:///d:/latex-lsp/texlab-dev","name":"texlab-dev"}]}}
```

**Comment by clason** [comment]
Hmm, if I do that, I get
```
Wed Sep  4 15:52:29 2019:["--->", 5, "texlab", {"method": "initialize",         "params": {"rootUri": "file:///XXX",         "capabilities": {"workspace": {"configuration": true, "applyEdit": true},       "textDocument": {"completion": {"completionItemKind": {"valueSet": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,  26]}}}}, "rootPath": "XXX", "processId":    49085, "trace": "off"}}]
Wed Sep  4 15:52:29 2019:["<---", 5, "texlab", {"response": {"id": 1,           "jsonrpc": "2.0", "error": {"code": -32602, "message": "Could not deserialize   parameter object"}}, "request": {"id": 1, "jsonrpc": "2.0", "method":           "initialize", "params": {"rootUri": "file:///XXX", "capabilities": {"workspace": {"configuration": true,           "applyEdit": true}, "textDocument": {"completion": {"completionItemKind":       {"valueSet": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,    19, 20, 21, 22, 23, 24, 25, 26]}}}}, "rootPath": "XXX", "processId": 49085, "trace": "off"}}}]
```

**Comment by clason** [comment]
Nevermind, copy&pasted the wrong `valueSet` -- if I drop the `26`, it works as advertised. Thanks!

**Comment by clason** [comment]
On a related note, would it make sense (and be possible) to use different `kind`s for BibTeX completions to distinguish `article`, `book`, `inproceedings`, `misc` etc.? (Assuming there are enough left?)

**Comment by pfoerster** [comment]
> On a related note, would it make sense (and be possible) to use different kinds for BibTeX completions to distinguish article, book, inproceedings, misc etc.? (Assuming there are enough left?)

There are about 50 different BibTeX types so I don't think it would make sense to use different kinds.

> Makes sense. The numbers are not so critical, but if all chapters/sections/etc. could be shown even without aux files (in this case without numbers), that would make this feature significantly more useful.

With the latest commit on the master, the symbol request does not require labels anymore. The labels are only used to extract the number from the AUX file. Everything else should work just fine without labels. In addition to that, special environments like the one you listed now show up the symbol list. Now, the `workspace/symbol` request can be used to filter by kind, e. g. searching for "section" shows all chapters, sections and subsections.

**Comment by clason** [comment]
> There are about 50 different BibTeX types so I don't think it would make sense to use different kinds.

By the latest biblatex specification, maybe -- BibTeX itself only knows 13 *entries*:

* article
* book
* booklet
* inbook
* incollection
* inproceedings
* manual
* mastersthesis
* misc
* phdthesis
* proceedings
* techreport
* unpublished

and I would group some of them (`book`/`booklet`/`proceedings`, `inbook`/`incollection`/`inproceedings`, `mastersthesis`/`phdthesis`, `unpublished`/`techreport`/`manual`/`misc`). 

I would definitely not go down the list of *fields* (`author`, `title`, etc.)

> With the latest commit on the master, the symbol request does not require labels anymore. The labels are only used to extract the number from the AUX file. Everything else should work just fine without labels. In addition to that, special environments like the one you listed now show up the symbol list. Now, the workspace/symbol request can be used to filter by kind, e. g. searching for "section" shows all chapters, sections and subsections.

🚀 ✨

**Comment by pfoerster** [comment]
> By the latest biblatex specification, maybe -- BibTeX itself only knows 13 entries:

While this should be true for BibTeX, BibLaTeX knows more than 13 entry types. 
See the `biblatex` package documentation (http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) for a complete list.
However, it should be possible to group them together like you did with the BibTeX types.

> my plan is to request vim-lsp to allow specifying custom kinds to override the generic ones.

Does this plan not conflict with the idea of using different kinds for BibTeX types?

**Comment by clason** [comment]
> While this should be true for BibTeX, BibLaTeX knows more than 13 entry types.
See the biblatex package documentation (http://mirrors.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) for a complete list.

Oh, yes -- keeping up with biblatex is a losing battle... Of course, it makes sense to be forward-looking. My thought was to start with the most used ones and leave the rarer ones as plain `reference`. But looking at the list, most of them can in fact be included in one of the groups (maybe adding `online` and/or `software`). 

> Does this plan conflict with the idea of using different kinds for BibTeX types?

Not sure, actually. For completion it should not, since vim-lsp would just be told to show, e.g., `equation` instead of `constant` for `21` (this is why I was asking for texlab's mappings).
It should be similar for `DocumentSymbols`, but I'm not clear whether the other direction, querying `WorkspaceSymbols`, would work as well.

**Comment by clason** [comment]
I've been playing around with `WorkspaceSymbols`, and I noticed that theorem-like environments are not showing their numbers (as opposed to equation and section-like symbols) -- I can go to `Equation (3.1)`, but not `Lemma 3.1`?

**Comment by pfoerster** [comment]
> I've been playing around with WorkspaceSymbols, and I noticed that theorem-like environments are not showing their numbers (as opposed to equations, figures, and section-like symbols) -- I can go to Equation (3.1), but not Lemma 3.1?

I cannot reproduce this at the moment. Do your theorem environments have a label? If not, then TexLab cannot know the number because there is no entry in the corresponding AUX file.
For example, the following document produces an (almost) empty AUX file:

`foo.tex:`

```tex
\documentclass{article}
\usepackage{amsmath}
\usepackage{amsthm}

\newtheorem{lemma}{Lemma}

\begin{document}

\begin{lemma}
    1 + 1 = 2
\end{lemma}

\end{document}

```

`foo.aux:`

```tex
\relax
```

**Comment by clason** [comment]
Yes, the specific Lemma has a label (and an aux file); I'm also not seeing *any* numbers on Lemmas, Theorems, Examples etc. It's a large, complicated multi-file document, though; I'll see if I can reduce it to a minimal example.

**Comment by clason** [comment]
You're right, it works in a single-file project. A different multi-file project has a similar (worse) issue, though.

**Comment by clason** [comment]
Here's a minimal example (including aux and vim-lsp log file; same behavior in VS Code, though).
[test.zip](https://github.com/latex-lsp/texlab/files/3590348/test.zip)

**Comment by pfoerster** [comment]
Thanks for the report. I found the issue. I am working on a fix.

**Comment by pfoerster** [comment]
1226fffc5512aaf50a93ae9fd4132036ed92054c should fix the issue.

**Comment by clason** [comment]
So it does! Thank you very much for the quick fix!

**Comment by clason** [comment]
(Here as well: If for you the suggestion on BibTeX kinds is `wontfix` (for now), this issue can be closed.)

**Comment by pfoerster** [comment]
> (Here as well: If for you the suggestion on BibTeX kinds is wontfix (for now), this issue can be closed.)

I don't think this is a wontfix. Grouping the entry types together should make it easier to navigate through the completion list.

**Comment by clason** [comment]
OK, didn't mean to pressure you! I just felt bad for having opened so many issues at once and was hoping to reduce the number a bit...

**Comment by clason** [comment]
Copied from #27 

It would be nice to have the global list of `workspaceSymbols` sorted by project order rather than alphabetically by file name: At the moment, if I have main.tex that includes -- in this order -- b.tex and a.tex, a workspaceSymbols request gives the (correctly sorted) symbols in a.tex before those in b.tex before those in main.tex, while the other way around would be more natural.

**Comment by clason** [comment]
Although this might be a client issue: VS Code sorts alphabetically by label only (no order of included files that I can see).

**Comment by pfoerster** [comment]
> Although this might be a client issue: VS Code sorts alphabetically by label only (no order of included files that I can see).

Unfortunately, VS Code sorts all symbols alphabetically and it seems there is no way to change it.

**Comment by clason** [comment]
Lucky for me that I'm using vi, then ;)

**Comment by pfoerster** [comment]
> It would be nice to have the global list of workspaceSymbols sorted by project order rather than alphabetically by file name: At the moment, if I have main.tex that includes -- in this order -- b.tex and a.tex, a workspaceSymbols request gives the (correctly sorted) symbols in a.tex before those in b.tex before those in main.tex, while the other way around would be more natural.

@clason  Can you try b30046bc77b91dde6c9856da89960fb9046f4ec0? It seems to be working for me.

**Comment by clason** [comment]
Sorry to say, it doesn't -- the files are no longer sorted alphabetically, but they're not in project order (not sure what order, though). It seems that the first one is always the current file -- maybe it's not starting parsing from the root node?

**Comment by clason** [comment]
I'm not using folders in this case. On my current machine (Linux), this seems fixed now; I'll check with the one I noticed the problem with (macOS) tonight.

I don't think that it was an issue with building the document, since I tested this with a pre-built project. I'm not sure how vim-lsp could implement this in this case, to be honest, since vim knows nothing of the relevant files... I think this is one of the cases where it would make sense to deviate from specification (or at least its recommendation) and implement file watching in the server?

The (long-term) alternative is to wait for neovim to include basic LSP functionality (planned for 0.5.0) and use that to built a special-purpose client into `vimtex` (which could trigger `didChangedWatchedFiles` also on the corresponding `aux` file if the `tex` file is changed).

**Comment by clason** [comment]
In any case, the issue seems fixed on macOS as well. 👍

**Comment by clason** [comment]
> Another thing, which could be problematic, is the workspace/didChangedWatchedFiles notification, which is sent from the client to the server when a watched file changes (in this case the AUX file). 

I've been thinking about this; it seems challenging, since compilation will possibly (likely) change _all_ aux files in a project, independent of the currently edited file. How does VS Code handle this?

What exact notification should the client send when it thinks (all) the aux files have changed? Then I could try to get it into vim-lsp.

(By the way, the upcoming version 3.15.0 of the specification includes client identification, so texlab could conceivably special case vim-lsp (if wanted).)

**Comment by pfoerster** [comment]
> I've been thinking about this; it seems challenging, since compilation will possibly (likely) change all aux files in a project, independent of the currently edited file. How does VS Code handle this?

VSCode has the concept of a workspace folder, which is sent to the server during the initialize request. It is probably used to implement file watching. However, Vim and a lot of other editors do not have this concept of a workspace, which makes it difficult to implement file watching on the client side in the case of LaTeX. For example, you could open a child file and the main file lies in another directory. Therefore, it would be pretty difficult for the client to find the main file without asking the server.
That's why, it would probably be better to implement file watching at the server side.

> What exact notification should the client send when it thinks (all) the aux files have changed?

The client sends a `workspace/didChangeWatchedFiles` notification to the server, whenever a file in the current workspace changes. To receive these notifications, the server has to register itself with a list of glob patterns, that can be used to filter the results. At the moment, TexLab registers for changes of `aux` and `log` files (log files are used to report errors using the `textDocument/publishDiagnostics` notification). As I said before, not all language clients have the concept of a workspace so implementing this request can be fairly difficult in the case of LaTeX.

> Should I open a new issue for that? (And also for the sorting? This issue is getting long.)

Yes, another issue would probably be better. I will work on eliminating the requirement of the `workspace/didChangeWatchedFiles` notification. The sorting could be a separate issue too. Then we could close this issue.

**Comment by clason** [comment]
> That's why, it would probably be better to implement file watching at the server side.

I agree in this case (not necessarily for changes, but to keep track of which files to rescan).

> Yes, another issue would probably be better. I will work on eliminating the requirement of the workspace/didChangeWatchedFiles notification. The sorting could be a separate issue too. Then we could close this issue.

That was the idea :)
